const userOptions = [
    {value: "type", default: "on", values: ["user"]},
    {value: "admin", default: "off", values: ["yes", "no"]},
    {value: "send_events", default: "on", values: ["yes", "no"]},
    {value: "echo_events", default: "on", values: ["yes", "no"]},
    {value: "marked", default: "off", values: ["yes", "no"]},
    {value: "startmuted", default: "off", values: ["yes", "no"]},
    {value: "music_on_hold_when_empty", default: "off", values: ["yes", "no"]},
    {value: "music_on_hold_class", default: "on", values: ["default"]},
    {value: "quiet", default: "off", values: ["yes", "no"]},
    {value: "hear_own_join_sound", default: "on", values: ["yes", "no"]},
    {value: "announce_user_count", default: "off", values: ["yes", "no"]},
    {value: "announce_user_count_all", default: "off", values: ["yes", "no"]},
    {value: "announce_only_user", default: "on", values: ["yes", "no"]},
    {value: "wait_marked", default: "off", values: ["yes", "no"]},
    {value: "end_marked", default: "off", values: ["yes", "no"]},
    {value: "end_marked_any", default: "off", values: ["yes", "no"]},
    {value: "dsp_drop_silence", default: "off", values: ["yes", "no"]},
    //{value: "dsp_talking_threshold", default: "on", values: ["128"]},
    //{value: "dsp_silence_threshold", default: "on", values: ["2000"]},
    {value: "talk_detection_events", default: "off", values: ["yes", "no"]},
    {value: "denoise", default: "off", values: ["yes", "no"]},
    {value: "jitterbuffer", default: "off", values: ["yes", "no"]},
    //{value: "pin", default: "off", values: ["1234"]},
    {value: "announce_join_leave", default: "off", values: ["yes", "no"]},
    {value: "announce_join_leave_review", default: "off", values: ["yes", "no"]},
    {value: "announcement", default: "off", values: ["input"]},
    {value: "timeout", default: "on", values: ["inputnumber"]},
    {value: "text_messaging", default: "off", values: ["yes", "no"]},
    {value: "answer_channel", default: "on", values: ["yes", "no"]},
]

export default userOptions