import { useContext, createContext, useEffect } from "react";
import { useAuth } from "toriphone-auth";

const ApiContext = createContext();

export const useApis = () => {
  return useContext(ApiContext);
};

// states
import useSidebarState from "./api/SidebarState.jsx";

// items per page
import useItemsPerPage from "./api/itemsPerPage.js";

// tenants
import useTenants from "./api/tenants.js";

// APIS

// status
import { useAgentdStatus } from "./api/agentd/status.js";
import { useCalldStatus } from "./api/calld/status.js";
import { useCallLogdStatus } from "./api/calllogd/status.js";
import { useChatdStatus } from "./api/chatd/Status.js";
import { useConfdStatus } from "./api/confd/Status.js";
import { useDirdStatus } from "./api/dird/Status.js";
import { usePlugindStatus } from "./api/plugind/Status.js";
import { useProvdStatus } from "./api/provd/Status.js";
import { useWebhookdStatus } from "./api/webhooks/Status.js";

// auth
import { useAuthGroups } from "./api/auth/Groups";
import { useAuthUsers } from "./api/auth/Users";
import { useBackends } from "./api/auth/Backends";
import { useExternal } from "./api/auth/External";
import { useIdp } from "./api/auth/Idp.js";
import { usePolicies } from "./api/auth/Policies";
import { useAuthTenants } from "./api/auth/Tenants.js";
import { useSessions } from "./api/auth/Sessions.js";

// calld
import { useCalls } from "./api/calld/calls.js";

// calllogd
import { useAgentStatistics } from "./api/calllogd/AgentStatistics.js";
import { useCdr } from "./api/calllogd/Cdr.js";
import { useQueuesStatistics } from "./api/calllogd/QueuesStatistics.js";
import { useRetention } from "./api/calllogd/Retention.js";

// confd
import { useAccessFeature } from "./api/confd/AccessFeature";
import { useAgents } from "./api/confd/Agents";
import { useApplications } from "./api/confd/Applications";
import { useAsterisk } from "./api/confd/Asterisk";
import { useBlocklist } from "./api/confd/Blocklist.js";
import { useCallfilters } from "./api/confd/CallFilters";
import { useCallPermissions } from "./api/confd/CallPermissions";
import { useCallpickup } from "./api/confd/Callpickup";
import { useConferences } from "./api/confd/Conferences";
import { useContexts } from "./api/confd/Contexts";
import { useDevices } from "./api/confd/Devices";
import { useDhcp } from "./api/confd/Dhcp.js";
import { useEndpoints } from "./api/confd/Endpoints";
import { useExtensions } from "./api/confd/Extensions";
import { useExternalApp } from "./api/confd/ExternalApp";
import { useFunckeys } from "./api/confd/Funckeys.js";
import { useGroups } from "./api/confd/Groups";
import { useGuests } from "./api/confd/Guests.js";
import { useIncalls } from "./api/confd/Incalls";
import { useInfos } from "./api/confd/Info";
import { useIngresses } from "./api/confd/Ingresses";
import { useIvrs } from "./api/confd/Ivrs";
import { useLdap } from "./api/confd/Ldap";
import { useLines } from "./api/confd/Lines";
import { useLocalization } from "./api/confd/Localization.js";
import { useMeetings } from "./api/confd/Meetings.js";
import { useMoh } from "./api/confd/Moh";
import { useOutcalls } from "./api/confd/Outcalls";
import { usePagings } from "./api/confd/Pagings";
import { useParkingLots } from "./api/confd/ParkingLots";
import { usePhoneNumbers } from "./api/confd/PhoneNumbers.js";
import { useProvisioning } from "./api/confd/Provisioning.js";
import { useQueues } from "./api/confd/Queues";
import { useRecordings } from "./api/confd/Recordings.js";
import { useRegisters } from "./api/confd/Registers.js";
import { useSchedules } from "./api/confd/Schedules";
import { useSip } from "./api/confd/Sip";
import { useSounds } from "./api/confd/Sounds";
import { useSwitchboards } from "./api/confd/Switchboards";
import { useTimezones } from "./api/confd/Timezones";
import { useTrunks } from "./api/confd/Trunks";
import { useUsers } from "./api/confd/Users";
import { useVoicemails } from "./api/confd/Voicemails";

// dird
import { useBackendsSources } from "./api/dird/BackendsSources.js";
import { useDirectories } from "./api/dird/Directories.js";
import { useDisplays } from "./api/dird/Displays.js";
import { usePhonebooks } from "./api/dird/Phonebooks.js";
import { useProfiles } from "./api/dird/Profiles.js";
import { useSources } from "./api/dird/Sources.js";

// plugind
import { usePlugins } from "./api/plugind/Plugin.js";

// provd
import { useProvdConfig } from "./api/provd/Provd.js";
import { useProvdConfigs } from "./api/provd/Configs.js";
import { useProvdDevices } from "./api/provd/Devices.js";
import { useProvdPlugins } from "./api/provd/Plugins.js";

// webhooks
import { useSubscriptions } from "./api/webhooks/Subscriptions.js";


export const ApiProvider = ({ children, i18nInstance }) => {
  // dependecies
  const { apiClient, Wazo } = useAuth();

  // sidebar State
  const { showSidebar, setShowSidebar, ToggleSidebarButton } = useSidebarState();

  // items per page
  const { itemsPerPage, setItemsPerPage } = useItemsPerPage();

  // tenants and tenantCurrent
  const { tenants, setTenants, tenantCurrent, setTenantCurrent, tenantsGet } = useTenants({ apiClient });

  // status
  const { agentdStatus, setAgentdStatus, agentdStatusGet } = useAgentdStatus({ apiClient });
  const { calldStatus, setCalldStatus, calldStatusGet } = useCalldStatus({ apiClient });
  const { callLogdStatus, setCallLogdStatus, callLogdStatusGet } = useCallLogdStatus({ apiClient });
  const { chatdStatus, setChatdStatus, chatdStatusGet } = useChatdStatus({ apiClient });
  const { confdStatus, setConfdStatus, confdStatusGet } = useConfdStatus({ apiClient });
  const { dirdStatus, setDirdStatus, dirdStatusGet } = useDirdStatus({ apiClient });
  const { plugindStatus, setPlugindStatus, plugindStatusGet } = usePlugindStatus({ apiClient });
  const { provdStatus, setProvdStatus, provdStatusGet } = useProvdStatus({ apiClient });
  const { webhookdStatus, setWebhookdStatus, webhookdStatusGet } = useWebhookdStatus({ apiClient });

  // access feature
  const {
    accessFeatures,
    setAccessFeatures,
    accessFeatureSelected,
    setAccessFeatureSelected,
    accessFeaturesGet,
    accessFeaturesPageGet,
    accessFeatureGet,
    accessFeatureAdd,
    accessFeatureEdit,
    accessFeatureDelete,
  } = useAccessFeature({ apiClient });

  // agents
  const {
    agents,
    setAgents,
    agentSelected,
    setAgentSelected,
    agentsSkillsAll,
    setAgentsSkillsAll,
    agentsSkills,
    setAgentsSkills,
    agentsSkillSelected,
    setAgentsSkillSelected,
    agentsGet,
    agentsPageGet,
    agentAdd,
    agentCreate,
    agentDelete,
    agentRemove,
    agentGet,
    agentEdit,
    agentUpdate,
    agentSkillAssociate,
    agentSkillDissociate,
    agentsSkillsGet,
    agentsSkillsPageGet,
    agentsSkillGet,
    agentsSkillsCreate,
    agentsSkillsUpdate,
    agentsSkillsDelete,
  } = useAgents({ apiClient });

  // agents statistics
  const {
    agentsStatistics,
    setAgentsStastistics,
    agentsStatisticsGet,
    agentStatistics,
    setAgentStastistics,
    agentStatisticsGet,
  } = useAgentStatistics({ apiClient });

  // application
  const {
    applications,
    setApplications,
    applicationSelected,
    setApplicationSelected,
    applicationsGet,
    applicationsPageGet,
    applicationGet,
    applicationCreate,
    applicationEdit,
    applicationDelete,
  } = useApplications({ apiClient });

  // asterisk
  const {
    asteriskConfbridgeWazoGet,
    asteriskConfbridgeWazoEdit,
    asteriskConfbridgeUserGet,
    asteriskConfbridgeUserEdit,
    asteriskFeaturesApplicationmapGet,
    asteriskFeaturesApplicationmapEdit,
    asteriskFeaturesFeaturemapGet,
    asteriskFeaturesFeaturemapEdit,
    asteriskFeaturesGeneralGet,
    asteriskFeaturesGeneralEdit,
    asteriskHepGeneralGet,
    asteriskHepGeneralEdit,
    asteriskIaxCallnumberlimitsGet,
    asteriskIaxCallnumberlimitsEdit,
    asteriskIaxGeneralGet,
    asteriskIaxGeneralEdit,
    asteriskPjsipDocGet,
    asteriskPjsipGlobalGet,
    asteriskPjsipGlobalEdit,
    asteriskPjsipSystemGet,
    asteriskPjsipSystemEdit,
    asteriskQueuesGeneralGet,
    asteriskQueuesGeneralEdit,
    asteriskRtpGeneralGet,
    asteriskRtpGeneralEdit,
    asteriskRtpIcehostcandidatesGet,
    asteriskRtpIcehostcandidatesEdit,
    asteriskSccpGeneralGet,
    asteriskSccpGeneralEdit,
    asteriskVoicemailGeneralGet,
    asteriskVoicemailGeneralEdit,
    asteriskVoicemailZonemessagesGet,
    asteriskVoicemailZonemessagesEdit,
  } = useAsterisk({ apiClient });

  // authGroups
  const {
    authGroups,
    setAuthGroups,
    authGroupSelected,
    setAuthGroupSelected,
    authGroupsGet,
    authGroupsPageGet,
    authGroupGet,
    authGroupAdd,
    authGroupCreate,
    authGroupEdit,
    authGroupUpdate,
    authGroupDelete,
    authGroupPoliciesGet,
    authGroupPolicyAssociate,
    authGroupPolicyDissociate,
    authGroupUsersGet,
    authGroupUserAssociate,
    authGroupUserDissociate,
  } = useAuthGroups({ apiClient });

  // authUsers
  const {
    authUsers,
    setAuthUsers,
    authUserSelected,
    setAuthUserSelected,
    authUsersGet,
    authUsersPageGet,
    authUserSearch,
    authUserGet,
    authUserAdd,
    authUserCreate,
    authUserEdit,
    authUserUpdate,
    authUserDelete,
    authUserEmailEdit,
    authUserEmailConfirmGet,
    authUserExternalGet,
    authUserExternalGoogleGet,
    authUserExternalGoogleAdd,
    authUserExternalGoogleDelete,
    authUserExternalMicrosoftGet,
    authUserExternalMicrosoftAdd,
    authUserExternalMicrosoftDelete,
    authUserExternalMobileGet,
    authUserExternalMobileAdd,
    authUserExternalMobileDelete,
    authUserExternalMobileSenderIdGet,
    authUserGroupsGet,
    authUserPasswordEdit,
    authUserPoliciesGet,
    authUserPoliciesAssociate,
    authUserPoliciesDissociate,
    authUserSessionsGet,
    authUserSessionDelete,
    authUserTokenGet,
    authUserTokenDelete,
    authUserPasswordResetGet,
    authUserPasswordReset,
    authUserRegister,
  } = useAuthUsers({ apiClient });

  // auth Tenants
  const {
    authTenants,
    setAuthTenants,
    authTenantSelected,
    setAuthTenantSelected,
    authTenantsGet,
    authTenantsPageGet,
    authTenantGet,
    authTenantAdd,
    authTenantEdit,
    authTenantDelete,
    authTenantDomains,
    setAuthTenantDomains,
    authTenantDomainGet,
  } = useAuthTenants({ tenantsGet, apiClient });

  // backends Auth
  const {
    backends,
    setBackends,
    backendLdap,
    setBackendLdap,
    backendsGet,
    backendLdapGet,
    backendLdapEdit,
    backendLdapDelete,
    backendSaml,
    setBackendSaml,
    backendSamlGet,
    backendSamlMetadataGet,
    backendSamlUrlGet,
    backendSamlCreate,
    backendSamlUpdate,
    backendSamlDelete
  } = useBackends({ apiClient });

  // backends sources
  const {
    backendsSources,
    setBackendsSources,
    backendSourcesSelected,
    setBackendSourcesSelected,
    backendsDirdGet,
    backendsSourcesGet,
    backendsSourceGet,
    backendsSourceAdd,
    backendsSourceEdit,
    backendsSourceDelete,
  } = useBackendsSources({ apiClient });

  // blocklist
  const {
    blocklistNumbers,
    setBlocklistNumbers,
    blocklistNumber,
    setBlocklistNumber,
    blocklistnumbersGet,
    blocklistnumbersPageGet,
    blocklistnumberGet,
  } = useBlocklist({ apiClient })

  // callFilters
  const {
    callfilters,
    setCallfilters,
    callfilterSelected,
    setCallfilterSelected,
    callfiltersGet,
    callfiltersPageGet,
    callfilterGet,
    callfilterAdd,
    callfilterCreate,
    callfilterEdit,
    callfilterUpdate,
    callfilterDelete,
    callfilterFallbacksGet,
    callfilterFallbacksEdit,
    callfilterRecipientsEdit,
    callfilterSurrogatesEdit,
  } = useCallfilters({ apiClient });

  // call permissions
  const {
    callPermissions,
    setCallPermissions,
    callPermissionSelected,
    setCallPermissionSelected,
    callPermissionsGet,
    callPermissionsPageGet,
    callPermissionAdd,
    callPermissionEdit,
    callPermissionDelete,
  } = useCallPermissions({ apiClient });

  // callpickup
  const {
    callpickups,
    setCallpickups,
    callpickupSelected,
    setCallpickupSelected,
    callpickupsGet,
    callpickupPageGet,
    callpickupGet,
    callpickupAdd,
    callpickupCreate,
    callpickupEdit,
    callpickupUpdate,
    callpickupDelete,
    callpickupInterceptorsGroupsEdit,
    callpickupInterceptorsUsersEdit,
    callpickupTargetsGroupsEdit,
    callpickupTargetsUsersEdit,
  } = useCallpickup({ apiClient });

  // calls
  const {
    calls,
    setCalls,
    callSelected,
    setCallSelected,
    callsGet,
    callsPageGet,
    callGet,
    callDelete,
    callRecordStart,
    callRecordStop,
  } = useCalls({ apiClient });

  // cdrs
  const {
    cdrs,
    setCdrs,
    cdrSelected,
    setCdrSelected,
    cdrsGet,
    cdrsPageGet,
    cdrGet,
    cdrRecordingGet,
    cdrRecordingDelete,
    cdrRecordsDelete,
    cdrRecordsExport,
  } = useCdr({ apiClient });

  // conferences
  const {
    conferencesAll,
    setConferencesAll,
    conferences,
    setConferences,
    conferenceSelected,
    setConferenceSelected,
    conferencesGet,
    conferencesPageGet,
    conferenceGet,
    conferenceAdd,
    conferenceCreate,
    conferenceEdit,
    conferenceUpdate,
    conferenceDelete,
    conferenceRemove,
    conferenceExtensionsAssociate,
    conferenceExtensionsDissociate,
  } = useConferences({ apiClient });

  // contexts
  const {
    contexts,
    setContexts,
    contextSelected,
    setContextSelected,
    contextsGet,
    contextsPageGet,
    contextGet,
    contextAdd,
    contextEdit,
    contextUpdate,
    contextDelete,
    contextAssociateContexts,
    contextRangeGet,
    contextRangeGroupGet,
    contextRangeQueueGet,
    contextRangeConferenceGet,
    contextRangeIncallGet,
  } = useContexts({ apiClient });

  // devices
  const {
    devices,
    setDevices,
    deviceSelected,
    setDeviceSelected,
    devicesUnallocated,
    setDevicesUnallocated,
    devicesGet,
    devicesPageGet,
    devicesUnallocatedGet,
    devicesUnallocatedAdd,
    deviceAdd,
    deviceGet,
    deviceEdit,
    deviceDelete,
    deviceResetAutoprov,
    deviceLinesGet,
    deviceSynchronize,
  } = useDevices({ apiClient });

  // dhcp
  const { dhcp, setDhcp, dhcpGet, dhcpEdit } = useDhcp({ apiClient });

  // directories
  const {
    directoriesSources,
    setDirectoriesSources,
    directoriesSourcesGet,
    directoriesSourcesUserGet,
    directoriesFavoritesGet,
    directoriesFavoritesAdd,
    directoriesFavoritesRemove,
    directoriesSearchContacts,
    directoriesSearchContactAsUser,
    directoriesHeadersGet,
    directoriesPersonalsGet,
    directoriesSearchReverseAsUser,
  } = useDirectories({ apiClient });

  // displays
  const {
    displays,
    setDisplays,
    displaySelected,
    setDisplaySelected,
    displaysGet,
    displayGet,
    displayAdd,
    displayEdit,
    displayDelete,
  } = useDisplays({ apiClient });

  // endpoints
  const {
    endpointsCustom,
    setEndpointsCustom,
    endpointsCustomGet,
    endpointCustomGet,
    endpointCustomAdd,
    endpointCustomEdit,
    endpointCustomDelete,
    endpointsIax,
    setEndpointsIax,
    endpointsIaxGet,
    endpointIaxGet,
    endpointIaxAdd,
    endpointIaxEdit,
    endpointIaxDelete,
    endpointsSccp,
    setEndpointsSccp,
    endpointsSccpGet,
    endpointSccpGet,
    endpointSccpAdd,
    endpointSccpEdit,
    endpointSccpDelete,
    endpointsSip,
    setEndpointsSip,
    endpointsSipGet,
    endpointSipGet,
    endpointSipAdd,
    endpointSipEdit,
    endpointSipDelete,
    endpointsTypeGet,
    endpointTypeGet,
    endpointTypeAdd,
    endpointTypeEdit,
    endpointTypeDelete,
    endpointsSipTemplatesAll,
    setEndpointsSipTemplatesAll,
    endpointsSipTemplates,
    setEndpointsSipTemplates,
    endpointSipTemplateSelected,
    setEndpointSipTemplateSelected,
    endpointsSipTemplatesGet,
    endpointsSipTemplatesPageGet,
    endpointSipTemplatesGet,
    endpointSipTemplatesAdd,
    endpointSipTemplatesEdit,
    endpointSipTemplatesDelete,
  } = useEndpoints({ apiClient });

  // extensions
  const {
    extensions,
    setExtensions,
    extensionSelected,
    setExtensionSelected,
    extensionsFeature,
    setExtensionsFeature,
    extensionsGet,
    extensionsPageGet,
    extensionGet,
    extensionCreate,
    extensionUpdate,
    extensionDelete,
    extensionsFeaturesGet,
    extensionsFeatureGet,
    extensionsFeatureEdit,
  } = useExtensions({ apiClient });

  // external apps
  const {
    externalApps,
    setExternalApps,
    externalAppSelected,
    setExternalAppSelected,
    externalAppsGet,
    externalAppsPageGet,
    externalAppGet,
    externalAppCreate,
    externalAppUpdate,
    externalAppDelete,
  } = useExternalApp({ apiClient });

  // external auth
  const {
    externals,
    setExternals,
    externalSelected,
    setExternalSelected,
    externalServices,
    setExternalServices,
    externalsGet,
    externalGet,
    externalAdd,
    externalEdit,
    externalDelete,
    externalUsersGet,
  } = useExternal({ apiClient });

  // funckeys
  const {
    funckeysTemplates,
    setFunckeysTemplates,
    funckeyTemplateSelected,
    setFunckeyTemplateSelected,
    funckeysDestinations,
    setFunckeysDestinations,
    funckeysDestinationsGet,
    funckeysTemplatesGet,
    funckeysTemplatesPageGet,
    funckeysTemplateGet,
    funckeysTemplateCreate,
    funckeysTemplateEdit,
    funckeysTemplateDelete,
    funckeysTemplatePositionGet,
    funckeysTemplatePositionUpdate,
    funckeysTemplatePositionDelete,
    funckeysTemplateUsersGet,
  } = useFunckeys({ apiClient });

  // groups
  const {
    groups,
    setGroups,
    groupsAll,
    setGroupsAll,
    groupSelected,
    setGroupSelected,
    groupsGet,
    groupsPageGet,
    groupAdd,
    groupCreate,
    groupEdit,
    groupUpdate,
    groupDelete,
    groupCallPermissionAssociate,
    groupCallPermissionsAssociate,
    groupCallPermissionDissociate,
    groupCallPermissionsDissociate,
    groupMembersUsersUpdate,
    groupFallbacksUpdate,
    groupExtensionAssociate,
    groupExtensionDissociate,
    groupSchedulesAssociate,
    groupSchedulesDissociate,
  } = useGroups({ apiClient });

  // guests
  const {
    guestsMeetingsAuthorizations,
    setGuestsMeetingsAuthorizations,
    guestsMeetingsAuthorizationsCreate,
    guestsMeetingsAuthorisationGet,
  } = useGuests({ apiClient });

  // idp
  const {
    idp,
    setIdp,
    idpGet,
    idpUsersAssociate,
    idpUserAssociate,
    idpUserDissociate
  } = useIdp({apiClient})

  // incalls
  const {
    incalls,
    setIncalls,
    incallSelected,
    setIncallSelected,
    incallsGet,
    incallsPageGet,
    incallGet,
    incallAdd,
    incallCreate,
    incallEdit,
    incallUpdate,
    incallDelete,
    incallRemove,
    incallExtensionAssociate,
    incallExtensionDissociate,
    incallScheduleAssociate,
    incallScheduleDissociate,
  } = useIncalls({ apiClient });

  // infos
  const { serverInfos, serverInfosGet } = useInfos({ apiClient });

  // ingresses
  const {
    ingresses,
    setIngresses,
    ingressSelected,
    setIgressSelected,
    ingressesGet,
    ingressGet,
    ingressAdd,
    ingressEdit,
    ingressDelete,
  } = useIngresses({ apiClient });

  // ivrs
  const { ivrs, setIvrs, ivrSelected, setIvrSelected, ivrsGet, ivrsPageGet, ivrGet, ivrAdd, ivrEdit, ivrDelete } = useIvrs({
    apiClient,
  });

  // ldap
  const { ldap, setLdap, ldapGet } = useLdap({ apiClient });

  // lines
  const {
    lines,
    setLines,
    lineSelected,
    setLineSelected,
    linesGet,
    linesPageGet,
    lineGet,
    lineAdd,
    lineEdit,
    lineDelete,
    lineDeleteRecursive,
    lineCreate,
    lineApplicationAssociate,
    lineApplicationDissociate,
    lineDevicesGet,
    lineDeviceAssociate,
    lineDeviceDissociate,
    lineEndpointsCustomAssociate,
    lineEndpointsCustomDissociate,
    lineEndpointsSccpAssociate,
    lineEndpointsSccpDissociate,
    lineEndpointsSipAssociate,
    lineEndpointsSipDissociate,
    lineExtensionsAdd,
    lineExtensionsAssociate,
    lineExtensionsDissociate,
  } = useLines({ apiClient });

  // localization
  const { localization, setLocalization, localizationGet, localizationUpdate } = useLocalization({ apiClient })

  // meetings
  const {
    meetings,
    setMeetings,
    meetingSelected,
    setMeetingSelected,
    meetingsGet,
    meetingsPageGet,
    meetingGet,
    meetingCreate,
    meetingUpdate,
    meetingDelete,
  } = useMeetings({ apiClient });

  // mohs
  const {
    mohs,
    setMohs,
    mohSelected,
    setMohSelected,
    mohsGet,
    mohsPageGet,
    mohGet,
    mohAdd,
    mohEdit,
    mohDelete,
    mohFileGet,
    mohFileUpload,
    mohFileDelete,
  } = useMoh({ apiClient, Wazo });

  // outcalls
  const {
    outcalls,
    setOutcalls,
    outcallSelected,
    setOutcallSelected,
    outcallsGet,
    outcallsPageGet,
    outcallGet,
    outcallAdd,
    outcallCreate,
    outcallEdit,
    outcallUpdate,
    outcallDelete,
    outcallRemove,
    outcallCallpermissionAssociate,
    outcallCallpermissionDissociate,
    outcallExtensionAssociate,
    outcallExtensionDissociate,
    outcallScheduleAssociate,
    outcallScheduleDissociate,
    outcallTrunksAssociate,
  } = useOutcalls({ apiClient });

  // pagings
  const {
    pagings,
    setPagings,
    pagingSelected,
    setPagingSelected,
    pagingsGet,
    pagingPageGet,
    pagingGet,
    pagingAdd,
    pagingCreate,
    pagingEdit,
    pagingUpdate,
    pagingDelete,
    pagingCallersEdit,
    pagingMembersEdit,
  } = usePagings({ apiClient });

  // parkingLots
  const {
    parkingLots,
    setParkingLots,
    parkingLotSelected,
    setParkingLotSelected,
    parkingLotsGet,
    parkingLotsPageGet,
    parkingLotGet,
    parkingLotAdd,
    parkingLotCreate,
    parkingLotEdit,
    parkingLotUpdate,
    parkingLotDelete,
    parkingLotRemove,
    parkingLotAssociateExtension,
    parkingLotDissociateExtension,
  } = useParkingLots({ apiClient });

  // phonebooks
  const {
    phonebooks,
    setPhonebooks,
    phonebookSelected,
    setPhonebookSelected,
    phonebookContacts,
    setPhonebookContacts,
    phonebookContactSelected,
    setPhonebookContactSelected,
    phonebooksGet,
    phonebooksPageGet,
    phonebookGet,
    phonebookAdd,
    phonebookEdit,
    phonebookDelete,
    phonebookContactsGet,
    phonebookContactsPageGet,
    phonebookContactAdd,
    phonebookContactEdit,
    phonebookContactDelete,
  } = usePhonebooks({ apiClient });

  // phoneNumbers
  const {
    phoneNumbers,
    setPhoneNumbers,
    phoneNumbersSelected,
    setPhoneNumbersSelected,
    phoneNumbersGet,
    phoneNumbersPageGet,
    phoneNumberGet,
    phoneNumberAdd,
    phoneNumberEdit,
    phoneNumberDelete,
    phoneNumbersRangeAdd,
  } = usePhoneNumbers({ apiClient });

  // plugins
  const { plugins, setPlugins, pluginsGet, pluginGet, pluginInstall, pluginReinstall, pluginUninstall } = usePlugins({
    apiClient,
  });

  // policies
  const {
    policiesAll,
    setPoliciesAll,
    policies,
    setPolicies,
    policySelected,
    setPolicySelected,
    policiesGet,
    policiesPageGet,
    policyGet,
    policyAdd,
    policyEdit,
    policyDelete,
    policyAclEdit,
    policyAclDelete,
  } = usePolicies({ apiClient });

  // profiles
  const {
    profiles,
    setProfiles,
    profileSelected,
    setProfileSelected,
    profilesGet,
    profileGet,
    profileAdd,
    profileEdit,
    profileDelete,
  } = useProfiles({ apiClient });

  // provdConfig
  const {
    provdConfigs,
    setProvdConfigs,
    provdConfigSelected,
    setProvdConfigSelected,
    provdConfigGet,
    provdConfigParamGet,
    provdConfigParamEdit,
    provdConfigFtpProxyUpdate,
    provdConfigHttpProxyUpdate,
    provdConfigHttpsProxyUpdate,
    provdConfigLocaleUpdate,
    provdConfigNatUpdate,
    provdConfigPluginServerUpdate,
    provdConfigProvisioningKeyUpdate,
  } = useProvdConfig({ apiClient });

  // provdConfigs
  const {
    provdCfgmgr,
    setProvdCgfmgr,
    provdCfgmgrConfig,
    setProvdCfmgrConfig,
    provdConfigMgrGet,
    provdConfigMgrAutocreate,
    provdConfigMgrConfigsGet,
    provdConfigMgrConfigGet,
    provdConfigMgrConfigGetRaw,
    provdConfigMgrConfigAdd,
    provdConfigMgrConfigEdit,
    provdConfigMgrConfigDelete,
  } = useProvdConfigs({ apiClient });

  // provdDevices
  const {
    provdDevmgr,
    setProvdDevmgr,
    provdDevmgrDevices,
    setProvdDevmgrDevices,
    provdDevmgrGet,
    provdDevmgrDevicesGet,
    provdDevmgrDeviceGet,
    provdDevmgrDeviceAdd,
    provdDevmgrDeviceEdit,
    provdDevmgrDeviceDelete,
    provdDevmgrDhcpInfo,
    provdDevmgrReconfigure,
    provdDevmgrSynchronize,
    provdDevmgrSynchronizeGet,
    provdDevmgrSynchronizeStop,
  } = useProvdDevices({ apiClient });

  // provdPlugins
  const {
    provdPluginMgr,
    setProvdPluginMgr,
    provdPluginService,
    setProvdPluginService,
    provdPluginsInstallable,
    setProvdPluginsInstallable,
    provdPluginsInstalled,
    setProvdPluginsInstalled,
    provdPlugins,
    setProvdPlugins,
    provdPluginSelected,
    setProvdPluginSelected,
    provdPluginMgrGet,
    provdPluginServiceGet,
    provdPluginsInstallableGet,
    provdPluginsInstallableUpdate,
    provdPluginsInstallableUpdateOperationDelete,
    provdPluginsInstallableUpdateOperationGetStatus,
    provdPluginsInstalledGet,
    provdPluginInstall,
    provdPluginInstallOperationDelete,
    provdPluginInstallOperationGetStatus,
    provdPluginUninstall,
    provdPluginUpgrade,
    provdPluginUpgradeOperationGetStatus,
    provdPluginUpgradeOperationDelete,
    provdPluginsGet,
    provdPluginGet,
    provdPluginGetInfo,
    provdPluginGetPackage,
    provdPluginPackageAdd,
    provdPluginPackageOperationGet,
    provdPluginPackageOperationDelete,
    provdPluginPackageInstallable,
    provdPluginPackageInstalled,
    provdPluginPackageDelete,
    provdPluginPackageUpgradeOperationGet,
    provdPluginPackageUpgradeOperationDelete,
    provdPluginReload,
  } = useProvdPlugins({ apiClient });

  // provisioning
  const { provisioningNetworking, setProvisioningNetworking, provisioningNetworkingGet, provisioningNetworkingEdit } =
    useProvisioning({ apiClient });

  // queues
  const {
    queuesAll,
    setQueuesAll,
    queues,
    setQueues,
    queueSelected,
    setQueueSelected,
    queuesSkills,
    setQueuesSkills,
    queueSkillSelected,
    setQueueSkillSelected,
    queuesGet,
    queuesPageGet,
    queueAdd,
    queueCreate,
    queueEdit,
    queueUpdate,
    queueDelete,
    queueExtensionAssociate,
    queueExtensionDissociate,
    queueFallbacksGet,
    queueFallbacksUpdate,
    queueMembersAgentAssociate,
    queueMembersAgentDissociate,
    queueMembersAgentsAssociate,
    queueMembersAgentsDissociate,
    queueMembersUserAssociate,
    queueMembersUserDissociate,
    queueMembersUsersAssociate,
    queueMembersUsersDissociate,
    queueSchedulesAssociate,
    queueSchedulesDissociate,
    queuesSkillrulesGet,
    queuesSkillrulesPageGet,
    queuesSkillruleAdd,
    queuesSkillruleDelete,
    queuesSkillruleUpdate,
  } = useQueues({ apiClient });

  // queues statistics
  const {
    queuesStatistics,
    setQueuesStastistics,
    queuesStatisticsGet,
    queueStatistics,
    setQueueStastistics,
    queueStatisticsGet,
    queueStatisticsQosGet
  } = useQueuesStatistics({ apiClient });

  // recordings
  const {
    recordingsAnnouncements,
    setRecordingsAnnouncements,
    recordingsAnnouncementsGet,
    recordingsAnnouncementsEdit,
  } = useRecordings({apiClient});

  // registers
  const {
    registersIaxs,
    setRegistersIaxs,
    registersIaxsGet,
    registersIaxGet,
    registersIaxAdd,
    registersIaxEdit,
    registersIaxDelete,
  } = useRegisters({ apiClient });

  // retention
  const {
    retention,
    setRetention,
    retentionGet,
    retentionUpdate,
  } = useRetention({ apiClient });

  // schedules
  const {
    schedules,
    setSchedules,
    scheduleSelected,
    setScheduleSelected,
    schedulesGet,
    schedulePageGet,
    scheduleAdd,
    scheduleEdit,
    scheduleDelete,
  } = useSchedules({ apiClient });

  // sessions
  const {
    sessions,
    setSessions,
    sessionsGet,
    sessionsPageGet,
    sessionDelete,
    sessionsUserGet,
    sessionsUserDelete
  } = useSessions({ apiClient });

  // sip
  const {
    sipTransportsAll,
    setSipTransportAll,
    sipTransports,
    setSipTransports,
    sipTransportSelected,
    setSipTransportSelected,
    sipTransportsGet,
    sipTransportsPageGet,
    sipTransportGet,
    sipTransportAdd,
    sipTransportEdit,
    sipTransportDelete,
  } = useSip({ apiClient });

  // sounds
  const {
    sounds,
    setSounds,
    soundSelected,
    setSoundSelected,
    soundsGet,
    soundsPageGet,
    soundCategoryGet,
    soundCategoryAdd,
    soundCategoryDelete,
    soundCategoryFileGet,
    soundCategoryFilePut,
    soundCategoryFileDelete,
    soundsLanguagesGet,
  } = useSounds({ apiClient, Wazo });

  // sources
  const { sources, setSources, sourceSelected, setSourceSelected, sourcesGet, sourcesPageGet } = useSources({ apiClient });

  // subscriptions
  const {
    subscriptions,
    setSubcriptions,
    subscriptionSelected,
    setSubscriptionSelected,
    subscriptionLogs,
    setSubscriptionLogs,
    subscriptionsGet,
    subscriptionsPageGet,
    subscriptionGet,
    subscriptionAdd,
    subscriptionEdit,
    subscriptionDelete,
    subscriptionLogsGet,
    subscriptionServicesGet,
  } = useSubscriptions({ apiClient });

  // switchboards
  const {
    switchboards,
    setSwitchboards,
    switchboardSelected,
    setSwitchboardSelected,
    switchboardsGet,
    switchboardsPageGet,
    switchboardGet,
    switchboardAdd,
    switchboardCreate,
    switchboardEdit,
    switchboardUpdate,
    switchboardDelete,
    switchboardFallbacksGet,
    switchboardFallbacksEdit,
    switchboardMembersEdit,
  } = useSwitchboards({ apiClient });

  // timezones
  const { timezones, timezonesGet } = useTimezones({ apiClient });

  // trunks
  const {
    trunks,
    setTrunks,
    trunkSelected,
    setTrunkSelected,
    trunksGet,
    trunksPageGet,
    trunkGet,
    trunkAdd,
    trunkCreate,
    trunkEdit,
    trunkUpdate,
    trunkDelete,
    trunkEndpointCustomAssociate,
    trunkEndpointCustomDissociate,
    trunkEndpointIaxAssociate,
    trunkEndpointIaxDissociate,
    trunkEndpointSipAssociate,
    trunkEndpointSipDissociate,
    trunkEndpointTypeAssociate,
    trunkEndpointTypeDissociate,
    trunkRegisterIaxAssociate,
    trunkRegisterIaxDissociate,
  } = useTrunks({ apiClient });

  // users
  const {
    users,
    setUsers,
    usersGet,
    usersPageGet,
    usersSearchByName,
    userCurrent,
    setUserCurrent,
    userGet,
    userCreate,
    userUpdate,
    userDelete,
    userDeleteRecursive,
    userAgentAssociate,
    userAgentDissociate,
    userCalleridsOutgoingGet,
    userCallpermissionsAssociate,
    userCallpermissionsDissociate,
    userFallbacksGet,
    userFallbacksUpdate,
    userForwardsGet,
    userForwardsUpdate,
    userForwardGet,
    userForwardUpdate,
    userFunckeysGet,
    userFunckeysUpdate,
    userFunckeyGet,
    userFunckeyCreate,
    userFunckeyDelete,
    userFunckeysTemplatesGet,
    userFunckeysTemplatesAssociate,
    userFunckeysTemplatesDissociate,
    userGroupsUpdate,
    userLinesAssociate,
    userLineAssociate,
    userLineDissociate,
    userScheduleAssociate,
    userScheduleDissociate,
    userServicesGet,
    userServicesUpdate,
    userServiceGet,
    userServiceUpdate,
    userVoicemailGet,
    userVoicemailAdd,
    userVoicemailAssociate,
    userVoicemailDissociate,
    userCreateVoicemail,
    userExternalAppsGet,
    userExternalAppGet,
    userExternalAppCreate,
    userExternalAppUpdate,
    userExternalAppDelete,
    userLineGet,
    userLineMainGet,
    usersExport,
    usersImport,
    usersSubscriptionsGet,
  } = useUsers({ apiClient, Wazo });

  // voicemails
  const {
    voicemails,
    setVoicemails,
    voicemailSelected,
    setVoicemailSelected,
    voicemailsGet,
    voicemailsPageGet,
    voicemailGet,
    voicemailAdd,
    voicemailCreate,
    voicemailEdit,
    voicemailUpdate,
    voicemailDelete,
    voicemailRemove,
  } = useVoicemails({ apiClient });

  // required value on init
  useEffect(() => {
    const fetch = async () => {
      // settingsSidebar Infos
      await serverInfosGet();
      // settingsSidebar tenants
      await tenantsGet();
      //usersGet();
      await contextsGet();
      // for applications and more like conferenceEdit
      await mohsGet();
      // for ivr sound label & destinationForm
      await soundsGet();
      // for user funckeys helper
      await groupsGet();
      await conferencesGet();
      await queuesGet();
    }
    fetch();
  }, []);

  // update apiclient
  useEffect(() => {
    if (tenantCurrent?.uuid) {
      apiClient.client.setTenant(tenantCurrent.uuid);
    }
    contextsGet();
    // for applications and more like conferenceEdit
    mohsGet();
    // for ivr sound label & destinationForm
    soundsGet();
    // for user funckeys helper
    groupsGet();
    conferencesGet();
    queuesGet();
  }, [tenantCurrent]);

  // logout on close window
  useEffect(() => {
    const handleBeforeUnload = (event) => {
      userLogout();
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, []);

  const value = {
    showSidebar,
    setShowSidebar,
    ToggleSidebarButton,
    itemsPerPage,
    setItemsPerPage,
    tenants,
    setTenants,
    tenantCurrent,
    setTenantCurrent,
    tenantsGet,
    agentdStatus,
    setAgentdStatus,
    agentdStatusGet,
    calldStatus,
    setCalldStatus,
    calldStatusGet,
    callLogdStatus,
    setCallLogdStatus,
    callLogdStatusGet,
    chatdStatus,
    setChatdStatus,
    chatdStatusGet,
    confdStatus,
    setConfdStatus,
    confdStatusGet,
    dirdStatus,
    setDirdStatus,
    dirdStatusGet,
    plugindStatus,
    setPlugindStatus,
    plugindStatusGet,
    provdStatus,
    setProvdStatus,
    provdStatusGet,
    webhookdStatus,
    setWebhookdStatus,
    webhookdStatusGet,
    accessFeatures,
    setAccessFeatures,
    accessFeatureSelected,
    setAccessFeatureSelected,
    accessFeaturesGet,
    accessFeaturesPageGet,
    accessFeatureGet,
    accessFeatureAdd,
    accessFeatureEdit,
    accessFeatureDelete,
    agents,
    setAgents,
    agentSelected,
    setAgentSelected,
    agentsSkillsAll,
    setAgentsSkillsAll,
    agentsSkills,
    setAgentsSkills,
    agentsSkillSelected,
    setAgentsSkillSelected,
    agentsGet,
    agentsPageGet,
    agentAdd,
    agentCreate,
    agentDelete,
    agentRemove,
    agentGet,
    agentEdit,
    agentUpdate,
    agentSkillAssociate,
    agentSkillDissociate,
    agentsSkillsGet,
    agentsSkillsPageGet,
    agentsSkillGet,
    agentsSkillsCreate,
    agentsSkillsUpdate,
    agentsSkillsDelete,
    agentsStatistics,
    setAgentsStastistics,
    agentsStatisticsGet,
    agentStatistics,
    setAgentStastistics,
    agentStatisticsGet,
    applications,
    setApplications,
    applicationSelected,
    setApplicationSelected,
    applicationsGet,
    applicationsPageGet,
    applicationGet,
    applicationCreate,
    applicationEdit,
    applicationDelete,
    asteriskConfbridgeWazoGet,
    asteriskConfbridgeWazoEdit,
    asteriskConfbridgeUserGet,
    asteriskConfbridgeUserEdit,
    asteriskFeaturesApplicationmapGet,
    asteriskFeaturesApplicationmapEdit,
    asteriskFeaturesFeaturemapGet,
    asteriskFeaturesFeaturemapEdit,
    asteriskFeaturesGeneralGet,
    asteriskFeaturesGeneralEdit,
    asteriskHepGeneralGet,
    asteriskHepGeneralEdit,
    asteriskIaxCallnumberlimitsGet,
    asteriskIaxCallnumberlimitsEdit,
    asteriskIaxGeneralGet,
    asteriskIaxGeneralEdit,
    asteriskPjsipDocGet,
    asteriskPjsipGlobalGet,
    asteriskPjsipGlobalEdit,
    asteriskPjsipSystemGet,
    asteriskPjsipSystemEdit,
    asteriskQueuesGeneralGet,
    asteriskQueuesGeneralEdit,
    asteriskRtpGeneralGet,
    asteriskRtpGeneralEdit,
    asteriskRtpIcehostcandidatesGet,
    asteriskRtpIcehostcandidatesEdit,
    asteriskSccpGeneralGet,
    asteriskSccpGeneralEdit,
    asteriskVoicemailGeneralGet,
    asteriskVoicemailGeneralEdit,
    asteriskVoicemailZonemessagesGet,
    asteriskVoicemailZonemessagesEdit,
    authGroups,
    setAuthGroups,
    authGroupSelected,
    setAuthGroupSelected,
    authGroupsGet,
    authGroupsPageGet,
    authGroupGet,
    authGroupAdd,
    authGroupCreate,
    authGroupEdit,
    authGroupUpdate,
    authGroupDelete,
    authGroupPoliciesGet,
    authGroupPolicyAssociate,
    authGroupPolicyDissociate,
    authGroupUsersGet,
    authGroupUserAssociate,
    authGroupUserDissociate,
    authUsers,
    setAuthUsers,
    authUserSelected,
    setAuthUserSelected,
    authUsersGet,
    authUsersPageGet,
    authUserSearch,
    authUserGet,
    authUserAdd,
    authUserCreate,
    authUserEdit,
    authUserUpdate,
    authUserDelete,
    authUserEmailEdit,
    authUserEmailConfirmGet,
    authUserExternalGet,
    authUserExternalGoogleGet,
    authUserExternalGoogleAdd,
    authUserExternalGoogleDelete,
    authUserExternalMicrosoftGet,
    authUserExternalMicrosoftAdd,
    authUserExternalMicrosoftDelete,
    authUserExternalMobileGet,
    authUserExternalMobileAdd,
    authUserExternalMobileDelete,
    authUserExternalMobileSenderIdGet,
    authUserGroupsGet,
    authUserPasswordEdit,
    authUserPoliciesGet,
    authUserPoliciesAssociate,
    authUserPoliciesDissociate,
    authUserSessionsGet,
    authUserSessionDelete,
    authUserTokenGet,
    authUserTokenDelete,
    authUserPasswordResetGet,
    authUserPasswordReset,
    authUserRegister,
    authTenants,
    setAuthTenants,
    authTenantSelected,
    setAuthTenantSelected,
    authTenantsGet,
    authTenantsPageGet,
    authTenantGet,
    authTenantAdd,
    authTenantEdit,
    authTenantDelete,
    authTenantDomains,
    setAuthTenantDomains,
    authTenantDomainGet,
    backends,
    setBackends,
    backendLdap,
    setBackendLdap,
    backendsGet,
    backendLdapGet,
    backendLdapEdit,
    backendLdapDelete,
    backendSaml,
    setBackendSaml,
    backendSamlGet,
    backendSamlMetadataGet,
    backendSamlUrlGet,
    backendSamlCreate,
    backendSamlUpdate,
    backendSamlDelete,
    backendsSources,
    setBackendsSources,
    backendSourcesSelected,
    setBackendSourcesSelected,
    backendsDirdGet,
    backendsSourcesGet,
    backendsSourceGet,
    backendsSourceAdd,
    backendsSourceEdit,
    backendsSourceDelete,
    blocklistNumbers,
    setBlocklistNumbers,
    blocklistNumber,
    setBlocklistNumber,
    blocklistnumbersGet,
    blocklistnumbersPageGet,
    blocklistnumberGet,
    callfilters,
    setCallfilters,
    callfilterSelected,
    setCallfilterSelected,
    callfiltersGet,
    callfiltersPageGet,
    callfilterGet,
    callfilterAdd,
    callfilterCreate,
    callfilterEdit,
    callfilterUpdate,
    callfilterDelete,
    callfilterFallbacksGet,
    callfilterFallbacksEdit,
    callfilterRecipientsEdit,
    callfilterSurrogatesEdit,
    callPermissions,
    setCallPermissions,
    callPermissionSelected,
    setCallPermissionSelected,
    callPermissionsGet,
    callPermissionsPageGet,
    callPermissionAdd,
    callPermissionEdit,
    callPermissionDelete,
    callpickups,
    setCallpickups,
    callpickupSelected,
    setCallpickupSelected,
    callpickupsGet,
    callpickupPageGet,
    callpickupGet,
    callpickupAdd,
    callpickupCreate,
    callpickupEdit,
    callpickupUpdate,
    callpickupDelete,
    callpickupInterceptorsGroupsEdit,
    callpickupInterceptorsUsersEdit,
    callpickupTargetsGroupsEdit,
    callpickupTargetsUsersEdit,
    calls,
    setCalls,
    callSelected,
    setCallSelected,
    callsGet,
    callsPageGet,
    callGet,
    callDelete,
    callRecordStart,
    callRecordStop,
    cdrs,
    setCdrs,
    cdrSelected,
    setCdrSelected,
    cdrsGet,
    cdrsPageGet,
    cdrGet,
    cdrRecordingGet,
    cdrRecordingDelete,
    cdrRecordsDelete,
    cdrRecordsExport,
    conferencesAll,
    setConferencesAll,
    conferences,
    setConferences,
    conferenceSelected,
    setConferenceSelected,
    conferencesGet,
    conferencesPageGet,
    conferenceGet,
    conferenceAdd,
    conferenceCreate,
    conferenceEdit,
    conferenceUpdate,
    conferenceDelete,
    conferenceRemove,
    conferenceExtensionsAssociate,
    conferenceExtensionsDissociate,
    contexts,
    setContexts,
    contextSelected,
    setContextSelected,
    contextsGet,
    contextsPageGet,
    contextGet,
    contextAdd,
    contextEdit,
    contextUpdate,
    contextDelete,
    contextAssociateContexts,
    contextRangeGet,
    contextRangeGroupGet,
    contextRangeQueueGet,
    contextRangeConferenceGet,
    contextRangeIncallGet,
    devices,
    setDevices,
    deviceSelected,
    setDeviceSelected,
    devicesUnallocated,
    setDevicesUnallocated,
    devicesGet,
    devicesPageGet,
    devicesUnallocatedGet,
    devicesUnallocatedAdd,
    deviceAdd,
    deviceGet,
    deviceEdit,
    deviceDelete,
    deviceResetAutoprov,
    deviceLinesGet,
    deviceSynchronize,
    dhcp,
    setDhcp,
    dhcpGet,
    dhcpEdit,
    directoriesSources,
    setDirectoriesSources,
    directoriesSourcesGet,
    directoriesSourcesUserGet,
    directoriesFavoritesGet,
    directoriesFavoritesAdd,
    directoriesFavoritesRemove,
    directoriesSearchContacts,
    directoriesSearchContactAsUser,
    directoriesHeadersGet,
    directoriesPersonalsGet,
    directoriesSearchReverseAsUser,
    displays,
    setDisplays,
    displaySelected,
    setDisplaySelected,
    displaysGet,
    displayGet,
    displayAdd,
    displayEdit,
    displayDelete,
    endpointsCustom,
    setEndpointsCustom,
    endpointsCustomGet,
    endpointCustomGet,
    endpointCustomAdd,
    endpointCustomEdit,
    endpointCustomDelete,
    endpointsIax,
    setEndpointsIax,
    endpointsIaxGet,
    endpointIaxGet,
    endpointIaxAdd,
    endpointIaxEdit,
    endpointIaxDelete,
    endpointsSccp,
    setEndpointsSccp,
    endpointsSccpGet,
    endpointSccpGet,
    endpointSccpAdd,
    endpointSccpEdit,
    endpointSccpDelete,
    endpointsSip,
    setEndpointsSip,
    endpointsSipGet,
    endpointSipGet,
    endpointSipAdd,
    endpointSipEdit,
    endpointSipDelete,
    endpointsTypeGet,
    endpointTypeGet,
    endpointTypeAdd,
    endpointTypeEdit,
    endpointTypeDelete,
    endpointsSipTemplatesAll,
    setEndpointsSipTemplatesAll,
    endpointsSipTemplates,
    setEndpointsSipTemplates,
    endpointSipTemplateSelected,
    setEndpointSipTemplateSelected,
    endpointsSipTemplatesGet,
    endpointsSipTemplatesPageGet,
    endpointSipTemplatesGet,
    endpointSipTemplatesAdd,
    endpointSipTemplatesEdit,
    endpointSipTemplatesDelete,
    extensions,
    setExtensions,
    extensionSelected,
    setExtensionSelected,
    extensionsFeature,
    setExtensionsFeature,
    extensionsGet,
    extensionsPageGet,
    extensionGet,
    extensionCreate,
    extensionUpdate,
    extensionDelete,
    extensionsFeaturesGet,
    extensionsFeatureGet,
    extensionsFeatureEdit,
    externalApps,
    setExternalApps,
    externalAppSelected,
    setExternalAppSelected,
    externalAppsGet,
    externalAppsPageGet,
    externalAppGet,
    externalAppCreate,
    externalAppUpdate,
    externalAppDelete,
    externals,
    setExternals,
    externalSelected,
    setExternalSelected,
    externalServices,
    setExternalServices,
    externalsGet,
    externalGet,
    externalAdd,
    externalEdit,
    externalDelete,
    externalUsersGet,
    funckeysTemplates,
    setFunckeysTemplates,
    funckeyTemplateSelected,
    setFunckeyTemplateSelected,
    funckeysDestinations,
    setFunckeysDestinations,
    funckeysDestinationsGet,
    funckeysTemplatesGet,
    funckeysTemplatesPageGet,
    funckeysTemplateGet,
    funckeysTemplateCreate,
    funckeysTemplateEdit,
    funckeysTemplateDelete,
    funckeysTemplatePositionGet,
    funckeysTemplatePositionUpdate,
    funckeysTemplatePositionDelete,
    funckeysTemplateUsersGet,
    groups,
    setGroups,
    groupsAll,
    setGroupsAll,
    groupSelected,
    setGroupSelected,
    groupsGet,
    groupsPageGet,
    groupAdd,
    groupCreate,
    groupEdit,
    groupUpdate,
    groupDelete,
    groupCallPermissionAssociate,
    groupCallPermissionsAssociate,
    groupCallPermissionDissociate,
    groupCallPermissionsDissociate,
    groupMembersUsersUpdate,
    groupFallbacksUpdate,
    groupExtensionAssociate,
    groupExtensionDissociate,
    groupSchedulesAssociate,
    groupSchedulesDissociate,
    guestsMeetingsAuthorizations,
    setGuestsMeetingsAuthorizations,
    guestsMeetingsAuthorizationsCreate,
    guestsMeetingsAuthorisationGet,
    idp,
    setIdp,
    idpGet,
    idpUsersAssociate,
    idpUserAssociate,
    idpUserDissociate,
    incalls,
    setIncalls,
    incallSelected,
    setIncallSelected,
    incallsGet,
    incallsPageGet,
    incallGet,
    incallAdd,
    incallCreate,
    incallEdit,
    incallUpdate,
    incallDelete,
    incallRemove,
    incallExtensionAssociate,
    incallExtensionDissociate,
    incallScheduleAssociate,
    incallScheduleDissociate,
    serverInfos,
    serverInfosGet,
    ingresses,
    setIngresses,
    ingressSelected,
    setIgressSelected,
    ingressesGet,
    ingressGet,
    ingressAdd,
    ingressEdit,
    ingressDelete,
    ivrs,
    setIvrs,
    ivrSelected,
    setIvrSelected,
    ivrsGet,
    ivrsPageGet,
    ivrGet,
    ivrAdd,
    ivrEdit,
    ivrDelete,
    ldap,
    setLdap,
    ldapGet,
    lines,
    setLines,
    lineSelected,
    setLineSelected,
    linesGet,
    linesPageGet,
    lineGet,
    lineAdd,
    lineEdit,
    lineDelete,
    lineDeleteRecursive,
    lineCreate,
    lineApplicationAssociate,
    lineApplicationDissociate,
    lineDevicesGet,
    lineDeviceAssociate,
    lineDeviceDissociate,
    lineEndpointsCustomAssociate,
    lineEndpointsCustomDissociate,
    lineEndpointsSccpAssociate,
    lineEndpointsSccpDissociate,
    lineEndpointsSipAssociate,
    lineEndpointsSipDissociate,
    lineExtensionsAdd,
    lineExtensionsAssociate,
    lineExtensionsDissociate,
    localization,
    setLocalization,
    localizationGet,
    localizationUpdate,
    meetings,
    setMeetings,
    meetingSelected,
    setMeetingSelected,
    meetingsGet,
    meetingsPageGet,
    meetingGet,
    meetingCreate,
    meetingUpdate,
    meetingDelete,
    mohs,
    setMohs,
    mohSelected,
    setMohSelected,
    mohsGet,
    mohsPageGet,
    mohGet,
    mohAdd,
    mohEdit,
    mohDelete,
    mohFileGet,
    mohFileUpload,
    mohFileDelete,
    outcalls,
    setOutcalls,
    outcallSelected,
    setOutcallSelected,
    outcallsGet,
    outcallsPageGet,
    outcallGet,
    outcallAdd,
    outcallCreate,
    outcallEdit,
    outcallUpdate,
    outcallDelete,
    outcallRemove,
    outcallCallpermissionAssociate,
    outcallCallpermissionDissociate,
    outcallExtensionAssociate,
    outcallExtensionDissociate,
    outcallScheduleAssociate,
    outcallScheduleDissociate,
    outcallTrunksAssociate,
    pagings,
    setPagings,
    pagingSelected,
    setPagingSelected,
    pagingsGet,
    pagingPageGet,
    pagingGet,
    pagingAdd,
    pagingCreate,
    pagingEdit,
    pagingUpdate,
    pagingDelete,
    pagingCallersEdit,
    pagingMembersEdit,
    parkingLots,
    setParkingLots,
    parkingLotSelected,
    setParkingLotSelected,
    parkingLotsGet,
    parkingLotsPageGet,
    parkingLotGet,
    parkingLotAdd,
    parkingLotCreate,
    parkingLotEdit,
    parkingLotUpdate,
    parkingLotDelete,
    parkingLotRemove,
    parkingLotAssociateExtension,
    parkingLotDissociateExtension,
    phonebooks,
    setPhonebooks,
    phonebookSelected,
    setPhonebookSelected,
    phonebookContacts,
    setPhonebookContacts,
    phonebookContactSelected,
    setPhonebookContactSelected,
    phonebooksGet,
    phonebooksPageGet,
    phonebookGet,
    phonebookAdd,
    phonebookEdit,
    phonebookDelete,
    phonebookContactsGet,
    phonebookContactsPageGet,
    phonebookContactAdd,
    phonebookContactEdit,
    phonebookContactDelete,
    phoneNumbers,
    setPhoneNumbers,
    phoneNumbersSelected,
    setPhoneNumbersSelected,
    phoneNumbersGet,
    phoneNumbersPageGet,
    phoneNumberGet,
    phoneNumberAdd,
    phoneNumberEdit,
    phoneNumberDelete,
    phoneNumbersRangeAdd,
    plugins,
    setPlugins,
    pluginsGet,
    pluginGet,
    pluginInstall,
    pluginReinstall,
    pluginUninstall,
    policiesAll,
    setPoliciesAll,
    policies,
    setPolicies,
    policySelected,
    setPolicySelected,
    policiesGet,
    policiesPageGet,
    policyGet,
    policyAdd,
    policyEdit,
    policyDelete,
    policyAclEdit,
    policyAclDelete,
    profiles,
    setProfiles,
    profileSelected,
    setProfileSelected,
    profilesGet,
    profileGet,
    profileAdd,
    profileEdit,
    profileDelete,
    provdConfigs,
    setProvdConfigs,
    provdConfigSelected,
    setProvdConfigSelected,
    provdConfigGet,
    provdConfigParamGet,
    provdConfigParamEdit,
    provdConfigFtpProxyUpdate,
    provdConfigHttpProxyUpdate,
    provdConfigHttpsProxyUpdate,
    provdConfigLocaleUpdate,
    provdConfigNatUpdate,
    provdConfigPluginServerUpdate,
    provdConfigProvisioningKeyUpdate,
    provdCfgmgr,
    setProvdCgfmgr,
    provdCfgmgrConfig,
    setProvdCfmgrConfig,
    provdConfigMgrGet,
    provdConfigMgrAutocreate,
    provdConfigMgrConfigsGet,
    provdConfigMgrConfigGet,
    provdConfigMgrConfigGetRaw,
    provdConfigMgrConfigAdd,
    provdConfigMgrConfigEdit,
    provdConfigMgrConfigDelete,
    provdDevmgr,
    setProvdDevmgr,
    provdDevmgrDevices,
    setProvdDevmgrDevices,
    provdDevmgrGet,
    provdDevmgrDevicesGet,
    provdDevmgrDeviceGet,
    provdDevmgrDeviceAdd,
    provdDevmgrDeviceEdit,
    provdDevmgrDeviceDelete,
    provdDevmgrDhcpInfo,
    provdDevmgrReconfigure,
    provdDevmgrSynchronize,
    provdDevmgrSynchronizeGet,
    provdDevmgrSynchronizeStop,
    provdPluginMgr,
    setProvdPluginMgr,
    provdPluginService,
    setProvdPluginService,
    provdPluginsInstallable,
    setProvdPluginsInstallable,
    provdPluginsInstalled,
    setProvdPluginsInstalled,
    provdPlugins,
    setProvdPlugins,
    provdPluginSelected,
    setProvdPluginSelected,
    provdPluginMgrGet,
    provdPluginServiceGet,
    provdPluginsInstallableGet,
    provdPluginsInstallableUpdate,
    provdPluginsInstallableUpdateOperationDelete,
    provdPluginsInstallableUpdateOperationGetStatus,
    provdPluginsInstalledGet,
    provdPluginInstall,
    provdPluginInstallOperationDelete,
    provdPluginInstallOperationGetStatus,
    provdPluginUninstall,
    provdPluginUpgrade,
    provdPluginUpgradeOperationGetStatus,
    provdPluginUpgradeOperationDelete,
    provdPluginsGet,
    provdPluginGet,
    provdPluginGetInfo,
    provdPluginGetPackage,
    provdPluginPackageAdd,
    provdPluginPackageOperationGet,
    provdPluginPackageOperationDelete,
    provdPluginPackageInstallable,
    provdPluginPackageInstalled,
    provdPluginPackageDelete,
    provdPluginPackageUpgradeOperationGet,
    provdPluginPackageUpgradeOperationDelete,
    provdPluginReload,
    provisioningNetworking,
    setProvisioningNetworking,
    provisioningNetworkingGet,
    provisioningNetworkingEdit,
    queuesAll,
    setQueuesAll,
    queues,
    setQueues,
    queueSelected,
    setQueueSelected,
    queuesSkills,
    setQueuesSkills,
    queueSkillSelected,
    setQueueSkillSelected,
    queuesGet,
    queuesPageGet,
    queueAdd,
    queueCreate,
    queueEdit,
    queueUpdate,
    queueDelete,
    queueExtensionAssociate,
    queueExtensionDissociate,
    queueFallbacksGet,
    queueFallbacksUpdate,
    queueMembersAgentAssociate,
    queueMembersAgentDissociate,
    queueMembersAgentsAssociate,
    queueMembersAgentsDissociate,
    queueMembersUserAssociate,
    queueMembersUserDissociate,
    queueMembersUsersAssociate,
    queueMembersUsersDissociate,
    queueSchedulesAssociate,
    queueSchedulesDissociate,
    queuesSkillrulesGet,
    queuesSkillrulesPageGet,
    queuesSkillruleAdd,
    queuesSkillruleDelete,
    queuesSkillruleUpdate,
    queuesStatistics,
    setQueuesStastistics,
    queuesStatisticsGet,
    queueStatistics,
    setQueueStastistics,
    queueStatisticsGet,
    queueStatisticsQosGet,
    recordingsAnnouncements,
    setRecordingsAnnouncements,
    recordingsAnnouncementsGet,
    recordingsAnnouncementsEdit,
    registersIaxs,
    setRegistersIaxs,
    registersIaxsGet,
    registersIaxGet,
    registersIaxAdd,
    registersIaxEdit,
    registersIaxDelete,
    retention,
    setRetention,
    retentionGet,
    retentionUpdate,
    schedules,
    setSchedules,
    scheduleSelected,
    setScheduleSelected,
    schedulesGet,
    schedulePageGet,
    scheduleAdd,
    scheduleEdit,
    scheduleDelete,
    sessions,
    setSessions,
    sessionsGet,
    sessionsPageGet,
    sessionDelete,
    sessionsUserGet,
    sessionsUserDelete,
    sipTransportsAll,
    setSipTransportAll,
    sipTransports,
    setSipTransports,
    sipTransportSelected,
    setSipTransportSelected,
    sipTransportsGet,
    sipTransportsPageGet,
    sipTransportGet,
    sipTransportAdd,
    sipTransportEdit,
    sipTransportDelete,
    sounds,
    setSounds,
    soundSelected,
    setSoundSelected,
    soundsGet,
    soundsPageGet,
    soundCategoryGet,
    soundCategoryAdd,
    soundCategoryDelete,
    soundCategoryFileGet,
    soundCategoryFilePut,
    soundCategoryFileDelete,
    soundsLanguagesGet,
    sources,
    setSources,
    sourceSelected,
    setSourceSelected,
    sourcesGet,
    sourcesPageGet,
    subscriptions,
    setSubcriptions,
    subscriptionSelected,
    setSubscriptionSelected,
    subscriptionLogs,
    setSubscriptionLogs,
    subscriptionsGet,
    subscriptionsPageGet,
    subscriptionGet,
    subscriptionAdd,
    subscriptionEdit,
    subscriptionDelete,
    subscriptionLogsGet,
    subscriptionServicesGet,
    switchboards,
    setSwitchboards,
    switchboardSelected,
    setSwitchboardSelected,
    switchboardsGet,
    switchboardsPageGet,
    switchboardGet,
    switchboardAdd,
    switchboardCreate,
    switchboardEdit,
    switchboardUpdate,
    switchboardDelete,
    switchboardFallbacksGet,
    switchboardFallbacksEdit,
    switchboardMembersEdit,
    timezones,
    timezonesGet,
    trunks,
    setTrunks,
    trunkSelected,
    setTrunkSelected,
    trunksGet,
    trunksPageGet,
    trunkGet,
    trunkAdd,
    trunkCreate,
    trunkEdit,
    trunkUpdate,
    trunkDelete,
    trunkEndpointCustomAssociate,
    trunkEndpointCustomDissociate,
    trunkEndpointIaxAssociate,
    trunkEndpointIaxDissociate,
    trunkEndpointSipAssociate,
    trunkEndpointSipDissociate,
    trunkEndpointTypeAssociate,
    trunkEndpointTypeDissociate,
    trunkRegisterIaxAssociate,
    trunkRegisterIaxDissociate,
    users,
    setUsers,
    usersGet,
    usersPageGet,
    usersSearchByName,
    userCurrent,
    setUserCurrent,
    userGet,
    userCreate,
    userUpdate,
    userDelete,
    userDeleteRecursive,
    userAgentAssociate,
    userAgentDissociate,
    userCalleridsOutgoingGet,
    userCallpermissionsAssociate,
    userCallpermissionsDissociate,
    userFallbacksGet,
    userFallbacksUpdate,
    userForwardsGet,
    userForwardsUpdate,
    userForwardGet,
    userForwardUpdate,
    userFunckeysGet,
    userFunckeysUpdate,
    userFunckeyGet,
    userFunckeyCreate,
    userFunckeyDelete,
    userFunckeysTemplatesGet,
    userFunckeysTemplatesAssociate,
    userFunckeysTemplatesDissociate,
    userGroupsUpdate,
    userLinesAssociate,
    userLineAssociate,
    userLineDissociate,
    userScheduleAssociate,
    userScheduleDissociate,
    userServicesGet,
    userServicesUpdate,
    userServiceGet,
    userServiceUpdate,
    userVoicemailGet,
    userVoicemailAdd,
    userVoicemailAssociate,
    userVoicemailDissociate,
    userCreateVoicemail,
    userExternalAppsGet,
    userExternalAppGet,
    userExternalAppCreate,
    userExternalAppUpdate,
    userExternalAppDelete,
    userLineGet,
    userLineMainGet,
    usersExport,
    usersImport,
    usersSubscriptionsGet,
    voicemails,
    setVoicemails,
    voicemailSelected,
    setVoicemailSelected,
    voicemailsGet,
    voicemailsPageGet,
    voicemailGet,
    voicemailAdd,
    voicemailCreate,
    voicemailEdit,
    voicemailUpdate,
    voicemailDelete,
    voicemailRemove,
  };

  return <ApiContext.Provider value={value}>{children}</ApiContext.Provider>;
};
