import React from 'react'

const SectionOptions = () => {

    // outbound_auth_section_options
    // registration_outbound_auth_section_options
    // auth_section_options
    const keyOptionsAuths = [
        'auth_type',
        'nonce_lifetime',
        'md5_cred',
        'password',
        'refresh_token',
        'oauth_clientid',
        'oauth_secret',
        'realm',
        'username'
      ]
    
      // registration_section_options
      const keyOptionsRegister = [
        'auth_rejection_permanent',
        'client_uri',
        'contact_header_params',
        'contact_user',
        'expiration',
        'fatal_retry_interval',
        'forbidden_retry_interval',
        'line',
        'max_retries',
        'outbound_proxy',
        'retry_interval',
        'server_uri',
        'support_outbound',
        'support_path',
        'transport'
      ]
    
      // identify_section_options
      const keyOptionsIdentifer = [
        'endpoint',
        'match',
        'match_header',
        'srv_lookups'
      ]

      // aor_section_options
      const keyOptionsAor = [
        'contact',
        'default_expiration',
        'mailboxes',
        'voicemail_extension',
        'maximum_expiration',
        'max_contacts',
        'minimum_expiration',
        'remove_existing',
        'remove_unavailable',
        'qualify_frequency',
        'qualify_timeout',
        'authenticate_qualify',
        'outbound_proxy',
        'support_path'
      ]
    
      // endpoint_section_options
      const keyOptionsEndpoint = [
        '100rel',
        'aggregate_mwi',
        'allow',
        'codec_prefs_incoming_offer',
        'codec_prefs_outgoing_offer',
        'codec_prefs_incoming_answer',
        'codec_prefs_outgoing_answer',
        'allow_overlap',
        'overlap_context',
        'aors',
        'auth',
        'callerid',
        'callerid_privacy',
        'callerid_tag',
        'context',
        'direct_media_glare_mitigation',
        'direct_media_method',
        'trust_connected_line',
        'send_connected_line',
        'connected_line_method',
        'direct_media',
        'disable_direct_media_on_nat',
        'disallow',
        'dtmf_mode',
        'media_address',
        'bind_rtp_to_media_address',
        'force_rport',
        'ice_support',
        'identify_by',
        'redirect_method',
        'mailboxes',
        'mwi_subscribe_replaces_unsolicited',
        'voiecmail_extension',
        'moh_suggest',
        'outbound_auth',
        'outbound_proxy',
        'rewrite_contact',
        'rtp_ipv6',
        'rtp_symmetric',
        'send_diversion',
        'send_history_info',
        'send_pai',
        'send_rpid',
        'rpid_immediate',
        'timers_min_se',
        'timers',
        'timers_sess_expires',
        'transport',
        'trust_id_inbound',
        'trust_id_outbound',
        'use_ptime',
        'use_avpf',
        'force_avp',
        'media_use_received_transport',
        'media_encryption',
        'media_endcryption_optimistic',
        'g726_non_standard',
        'inband_progress',
        'call_group',
        'pickup_group',
        'named_pickup_group',
        'device_state_busy_at',
        't38_udptl_ec',
        't38_udptl_maxdatagram',
        'fax_detect',
        'fax_detect_timeout',
        't38_udptl_nat',
        't38_udptl_ipv6',
        't38_bind_udptl_to_media_address',
        'tone_zone',
        'language',
        'one_touch_recording',
        'record_on_feature',
        'record_off_feature',
        'rtp_engine',
        'allow_transfer',
        'user_eq_phone',
        'moh_passthrough',
        'sdp_owner',
        'sdp_session',
        'tos_audio',
        'tos_video',
        'cos_audio',
        'cos_video',
        'sub_min_expiry',
        'from_user',
        'mwi_from_user',
        'from_domain',
        'dtls_verify',
        'dtls_rekey',
        'dtls_auto_generate_cert',
        'dtls_cert_file',
        'dtls_private_key',
        'dtls_cipher',
        'dtls_ca_file',
        'dtls_ca_path',
        'dtls_setup',
        'dtls_fingerprint',
        'srtp_tag_32',
        'set_var',
        'message_context',
        'accountcode',
        'preferred_codec_only',
        'incoming_call_offer_pref',
        'ougoing_call_offer_pref',
        'rtp_keepalive',
        'rtp_timeout',
        'rtp_timeout_hold',
        'acl',
        'deny',
        'permit',
        'contact_acl',
        'contact_deny',
        'contact_permit',
        'subscribe_context',
        'contact_user',
        'asymmetric_rtp_codec',
        'rtcp_mux',
        'refer_blind_progress',
        'notify_early_inuse_ringing',
        'max_audio_streams',
        'max_video_streams',
        'bundle',
        'webrtc',
        'incoming_mwi_mailbox',
        'follow_early_media_fork',
        'accept_multiple_adp_answers',
        'supress_q850_reason_headers',
        'ignore_183_without_sdp',
        'stir_shaken',
        'stir_shaken_profile',
        'allow_unauthenticated_options',
        'security_negotiation',
        'security_mechanisms',
        'geoloc_outgoing_call_profile',
        'send_aoc'
      ]

  return {
    keyOptionsAuths,
    keyOptionsRegister,
    keyOptionsIdentifer,
    keyOptionsAor,
    keyOptionsEndpoint
  }
}

export default SectionOptions